#!/bin/bash
set -e
if [ -z $MMPATH ]; then
    echo "The MMPATH environment variable must be set for the environment script to work."
    echo "Please set 'export MMPATH=<path to march-madness repo>' before continuing"
    exit 1
fi
echo "-> Using MMPATH=$MMPATH"
cd $MMPATH/codebase
if [ ! -d "mm_env" ]; then
    python3 -m venv mm_env 
fi
source mm_env/bin/activate
pip install -r deps.txt
cd python
pip install .
cd ..
deactivate
echo "-> Done"
